# Generated by Django 4.1.8 on 2023-04-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('description', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelCourses',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'level_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'payment_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('register_id', models.IntegerField(primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'register_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_site.courses')),
            ],
            options={
                'db_table': 'course_categories',
                'managed': False,
            },
        ),
    ]
